export const state = {
  wasmReady: false,
  templateMode: false,
  currentHeading: null,
  compassTarget: 0,
  showCompass: true,
  recognition: null,
  isListening: false,
  voiceFinalTranscript: '',
  savedTemplates: [],
  scanCount: 0,
  templateCount: 0,
  saveCount: 0,
  flashlightTrack: null,
  isOnline: navigator.onLine,
  lastDetection: null,
  detectionWorker: null,
  captureCanvas: null,
  captureCtx: null,
  workerReady: false,
  frameSkip: 0,
  FRAME_SKIP: 3,
};